// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

package order

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceDiscovery struct {
	OrderServiceUri      string   `protobuf:"bytes,1,opt,name=order_service_uri,json=orderServiceUri,proto3" json:"order_service_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDiscovery) Reset()         { *m = ServiceDiscovery{} }
func (m *ServiceDiscovery) String() string { return proto.CompactTextString(m) }
func (*ServiceDiscovery) ProtoMessage()    {}
func (*ServiceDiscovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

func (m *ServiceDiscovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDiscovery.Unmarshal(m, b)
}
func (m *ServiceDiscovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDiscovery.Marshal(b, m, deterministic)
}
func (m *ServiceDiscovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDiscovery.Merge(m, src)
}
func (m *ServiceDiscovery) XXX_Size() int {
	return xxx_messageInfo_ServiceDiscovery.Size(m)
}
func (m *ServiceDiscovery) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDiscovery.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDiscovery proto.InternalMessageInfo

func (m *ServiceDiscovery) GetOrderServiceUri() string {
	if m != nil {
		return m.OrderServiceUri
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceDiscovery)(nil), "order.ServiceDiscovery")
}

func init() { proto.RegisterFile("order/order.proto", fileDescriptor_fa47a2077d8980ed) }

var fileDescriptor_fa47a2077d8980ed = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2f, 0x4a, 0x49,
	0x2d, 0xd2, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x1d,
	0x97, 0x40, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x4b, 0x66, 0x71, 0x72, 0x7e, 0x59, 0x6a,
	0x51, 0xa5, 0x90, 0x16, 0x54, 0x7d, 0x7c, 0x31, 0x44, 0x26, 0xbe, 0xb4, 0x28, 0x53, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x88, 0x1f, 0x2c, 0x01, 0xd5, 0x11, 0x5a, 0x94, 0x99, 0xc4, 0x06, 0x36,
	0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x85, 0x05, 0x5f, 0x62, 0x00, 0x00, 0x00,
}
